---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: eslint-3
    config:
      extensions:
      - ".js"
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**/*.js"
exclude_paths:
- "src/**/*.spec.js"
- config/
- node_modules/
- reports/


